version: "3"
services:
    nginx:
        image: nginx:stable-alpine
        container_name: private-content-bot-nginx
        restart: unless-stopped
        ports:
            - 80:80
        volumes:
            - ./app:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    mysql:
        image: mysql:8.0
        container_name: private-content-bot-mysql
        restart: unless-stopped
        command: --max_allowed_packet=16M
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: bot
            MYSQL_DATABASE: bot
            MYSQL_USER: bot
            MYSQL_PASSWORD: bot

    php:
        container_name: private-content-bot-php
        restart: unless-stopped
        build: docker/php
        links:
            - mysql
        volumes:
            - ./app:/var/www/html
        depends_on:
            - mysql

    ngrok:
        container_name: private-content-bot-ngrok
        image: ngrok/ngrok:3
        restart: unless-stopped
        command:
            - "start"
            - "--all"
            - "--config"
            - "/etc/ngrok.yml"
        volumes:
            - ./docker/ngrok/ngrok.yml:/etc/ngrok.yml
        ports:
            - 4040:4040
        extra_hosts:
            - "host.docker.internal:host-gateway"
