monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@staging:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: critical
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: critical
                formatter: monolog.formatter.json

when@dev:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: critical
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: critical
                formatter: monolog.formatter.json
